version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./agenciaViagens
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUN_TESTS=${RUN_TESTS}
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -c "
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        if [ \"$RUN_TESTS\" = \"true\" ]; then
          sleep 5 && pytest tests --disable-warnings || true
        fi
        wait
      "

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
